### ISSUE TITLE
WebSocket reconnect Button suggestion

### ISSUE THREAD

**Issue by Diclo** [dima-dencep/online-emotes#12]
add a button that allows reconnection with the web socket

[https://i.imgur.com/LBvByZG.png](url)

**Comment by dima-dencep** [comment]
The mod will automatically connect to websocket when the connection is lost

**Comment by Diclo** [comment]
in fact that's not working, I was going to make a bug post about that topic

**Comment by dima-dencep** [comment]
🤨

**Comment by Diclo** [comment]
for example the default mod reconnects after 15 seconds, but still does not make the reconnection
https://i.imgur.com/G3G65jI.png

**Comment by dima-dencep** [comment]
Do you play on a regular server (not through essential, e4me, etc)?

**Comment by Diclo** [comment]
normal server "play.catcraft.net" 
i think they used velocity but no !00% sure

if I login and out of the server it reconnects, but of course that's not the idea xD

**Comment by dima-dencep** [comment]
I get it, with the update to 1.20.2 this will be fixed

**Comment by Diclo** [comment]
thanks for the patience and this project is amazing, being able to use emotes so free is great
