### ISSUE TITLE
Incorrect head position when playing emote

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [dima-dencep/online-emotes#16]
### Версия Minecraft.

1.20.1

### Версия Emotecraft.

2.2.7-b.build.50

### Версия Online Emotes.

2.1.2

### Что произошло?

![image](https://github.com/dima-dencep/online-emotes/assets/51203385/c3b6748b-43c6-4f66-9a20-35188c627356)

После установки мода обнаружил, что головы игроков оказываются свёрнутыми куда-то назад... хотя до этого они были нормально повёрнуты... всё исправляется после того, как они снова головой повернут куда-нибудь.

### Связанный журнал.

[latest.log](https://github.com/dima-dencep/online-emotes/files/13198260/latest.log)
(примерное время использования мода — 29.10.2023 16:44)

### Дополнительная информация.

Ядро:
fabric-loader-0.14.24-1.20.1

Моды:
cloth-config-11.1.106,
fabric-api-0.83.1+1.20.1,
modmenu-7.2.2,
stendhal-1.4.0-1.20,
yet-another-config-lib-fabric-3.2.1+1.20

Сервер:
play.spworlds.ru

**Comment by dima-dencep** [comment]
Please test on `mc.hypixel.net` or other vanilla servers
