### ISSUE TITLE
Possible update?

### ISSUE THREAD

**Issue by Diclo** [dima-dencep/online-emotes#17]
Sorry, I know you had mentioned that you would maintain the project for a few more months until making a decision about it, but I was wondering if there might be a possibility of a potential update to versions 1.20.5 and/or 1.21?

**Comment by dima-dencep** [comment]
There will be an update, kosmX is refactoring the protocol right now and online emotes are very sensitive to that, so I'm waiting

**Comment by dima-dencep** [comment]
I'll close this issue when I release the update...

**Comment by Diclo** [comment]
Great, and thank you for the response. Have a good day! c:
