### ISSUE TITLE
Could/should/would Online Emotes ever be merged into Emotecraft?

### ISSUE THREAD

**Issue by RaptaG** [dima-dencep/online-emotes#2]
Just asking..

**Comment by dima-dencep** [comment]
no

**Comment by DearFox** [comment]
But did the developer Emotecraft refuse this feature?  I'm sure I remember that he wanted to add essentially the function that this mod implements

**Comment by dima-dencep** [comment]
I don't know, this mod was originally made for private use, but then I published it
