### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by Diclo** [dima-dencep/online-emotes#21]
### Minecraft version.

1.21

### Emotecraft version.

no emotecraft-for-MC1.21-2.5-fabric

### Online Emotes version.

online-emotes-3.1.0+mc1.20.4-fabric

### What happened?

 when moving from the lobby to the survival server, it crashes

### Relevant logs

[https://pastebin.com/zVfJKTUf](url)

### Additional information

I was trying different things and put NoEmotecraft 1.21 with Online Emotecraft 1.20.4. Both start, and I can even enter the server lobbies, and it shows the mod connected to the emote server. However, when moving from the lobby to the survival server, it crashes with this result. Maybe this can be useful for the future update xD.

**Comment by dima-dencep** [comment]
Online Emotes supports only official EmoteCraft

**Comment by dima-dencep** [comment]
Reopened to track the update to 1.21

**Comment by ShrikerChestTrees** [comment]
> Online Emotes supports only official EmoteCraft

What should I do if Emotecraft does not have version 1.21-1.21.1?

**Comment by ShrikerChestTrees** [comment]
Maybe through NoEmotecraft (a fork of Emotecraft on 1.21) will work?

**Comment by dima-dencep** [comment]
Try and see

**Comment by Diclo** [comment]
Aside from the saved emotes in the wheel showing up as invalid (nothing critical, just need to set them again xD), everything's fine. Emotes are visible across versions without any issues.

**Comment by dima-dencep** [comment]
NoEmotecraft is not a usable fork, I can safely say it's the reason for all the problems
