### ISSUE TITLE
Upload emote server's source code

### ISSUE THREAD

**Issue by RaptaG** [dima-dencep/online-emotes#6]
I opened this issue to track:

---

- **Where is the source code of the «emote server» to which the mod connects?**
> Not available anywhere yet (mostly because of the quality of the code), but will be available soon!

---

this, that is mentioned in the README. Not meant to add pressure, but for people who are interested in updates on this to subscribe in order to get notified.

**Comment by dima-dencep** [comment]
Am I correct in assuming that you only need the server code to keep track of its updates?

**Comment by RaptaG** [comment]
um, yes pretty much

**Comment by DearFox** [comment]
I think even if the server source code is bad at the moment, post it - then interested people can help you, point out problems.  besides, it is interesting to observe the development and history of commits.  And also anyone can deploy their own server if they need it.

**Comment by dima-dencep** [comment]
Own servers for this mod are one of the reasons why the server part with closed code

**Comment by DearFox** [comment]
> Own servers for this mod are one of the reasons why the server part with closed code

That is, you do not plan to open source the server part?

**Comment by dima-dencep** [comment]
It will happen, but I don't know when.

**Comment by dima-dencep** [comment]
Right now there are no plans to open up the server code as online-emotes is part of RedlanceMinecraft's modular infrastructure and even if we publish it, it will take a lot of effort for you to run it on your computer, if you still want it I can share some parts of it with you privately.

**Comment by dima-dencep** [comment]
> I think even if the server source code is bad at the moment, post it - then interested people can help you, point out problems.

There are quite few people willing to maintain a custom server on netty these days, I've gained a lot of experience over the year and also now prefer java's built-in websocket api and will rewrite the mod for it soon
