### ISSUE TITLE
Server reliability

### ISSUE THREAD

**Issue by RaptaG** [dima-dencep/online-emotes#7]
I have some questions regarding the emote server:

- Do you self host the emote server? Do you have a paid plan on a cloud service? How long do you plan to maintain it?
- If the server goes down is there a backup plan?
- Is the server capable of supporting 10 simultaneous players emoting on different servers? 100? 1000?
- Where is the emote server hosted?
- Can you think of any other reasons why a modpack should not include this mod?

Please take your time and try to answer as many questions as you can..

**Comment by dima-dencep** [comment]
What makes you think modpacks can't include this mod?

**Comment by dima-dencep** [comment]
Also, at the moment, the server handles 30 players (I can not know which servers they are on)

**Comment by RaptaG** [comment]
> What makes you think modpacks can't include this mod?

I don't know, I'm just asking whether there would be performance drawbacks on the long run

**Comment by DearFox** [comment]
> > What makes you think modpacks can't include this mod?
> 
> I don't know, I'm just asking whether there would be performance drawbacks on the long run

I think you can always write your server on rust(🚀)

**Comment by dima-dencep** [comment]
After some time, I came back here to say that the very first version of the mod is still supported, albeit with not too many limitations.

The server has been running more than stable for over a year now, with only occasional interruptions for software updates (netty, gson, java)
> https://status.redlance.org/

According to CloudFlare statistics, in the last 30 days, the server has handled just over 900,000 requests and delivered 483GB of traffic.
